services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/drf_project
    env_file:
        - ./.env
    ports:
      - 8000:8000
    depends_on:
      - elasticsearch
      - redis
      - db
    networks:
      - elastic

  elasticsearch:
    image: elasticsearch:7.14.0
    volumes:
      - ./data/elastic:/var/lib/elasticsearch/data
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
    networks:
      - elastic

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - elastic

  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - elastic

volumes:
  postgres_data:

networks:
  elastic:
    driver: bridge
