# Generated by Django 5.0.6 on 2024-07-02 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_readlist_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readlist',
            name='date_added',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
