# Generated by Django 5.0.6 on 2024-07-03 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_readlist_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readlist',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
